"use client";
import Link from "next/link";
import Image from "next/image";
import { ArrowLeft } from "lucide-react";
const FONT=`@import url('https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=DM+Sans:ital,opsz,wght@0,9..40,400;0,9..40,500;0,9..40,600;0,9..40,700;0,9..40,800&display=swap');`;
const c={bg:"#F8F6F1",text:"#111214",sub:"#4A4F5C",muted:"#888E9C",accent:"#2563EB",border:"#E3DDD2"};
export default function Privacy(){return(<><style>{FONT}</style><style>{CSS}</style><div className="lW">
  <nav className="lN"><div className="cnt lNI"><Link href="/" className="lBr"><div className="lLo"><Image src="/omela-logo-mark.png" alt="Omela" width={28} height={28} style={{width:"100%",height:"100%",objectFit:"contain"}}/></div><span className="lBrN">Omela</span></Link><Link href="/" className="lBk"><ArrowLeft size={14}/>Back</Link></div></nav>
  <main className="lM"><div className="cnt lC">
    <p className="lUp">Last updated: 3 April 2026</p>
    <h1 className="serif lTi">Privacy Notice</h1>
    <p className="lIn">This notice explains how Omela ("we", "us") collects, uses, and protects your personal information when you use Laura and our services. Omela is committed to compliance with the UK General Data Protection Regulation (UK GDPR) and the Data Protection Act 2018.</p>
    <div className="lBadges"><span className="lBadge">UK GDPR Compliant</span><span className="lBadge">ICO Registered</span></div>
    <section className="lS"><h2>1. Who we are</h2><p>Omela is a digital health company building Laura, a care navigation platform. For the purposes of UK data protection law, Omela is the data controller responsible for your personal information. We are registered with the Information Commissioner's Office (ICO), the UK's independent authority for data protection. Contact: notice@omela.ai. Location: United Kingdom.</p></section>
    <section className="lS"><h2>2. What we collect</h2><p>We collect information you provide directly: your email address, the role you select (patient, provider, or developer), and any health-related information you share during conversations with Laura. We also collect technical data automatically: device type, browser, pages visited, and approximate location derived from your IP address. If you purchase credits, Stripe processes your payment information. We do not store card details.</p></section>
    <section className="lS"><h2>3. Lawful basis for processing</h2><p>We process your data under the following lawful bases as defined by Article 6 of the UK GDPR. Consent: when you join our waitlist, start a conversation with Laura, or provide health-related information. Legitimate interests: to operate, improve, and secure our services, provided these interests do not override your rights. Contractual necessity: where processing is required to provide services you have requested. Legal obligation: where required by law. For health-related data (special category data under Article 9), we rely on your explicit consent before processing.</p></section>
    <section className="lS"><h2>4. How we use your information</h2><p>We use your information to provide Laura's care navigation services, manage your account and credit balance, communicate service updates, respond to support requests, improve Laura's accuracy and safety, ensure platform security, and comply with legal obligations. We do not sell your personal data. We do not use your data for advertising.</p></section>
    <section className="lS"><h2>5. Data sharing</h2><p>We share data with service providers who help us operate Laura: cloud hosting (Vercel), database (Neon), AI model providers (for Laura's responses), and payment processing (Stripe). These providers process data only on our instructions and are contractually bound to protect it. We may share data with healthcare providers only when you explicitly request Laura to submit a callback, registration, or prescription request on your behalf. We may disclose data to legal authorities where required by law.</p></section>
    <section className="lS"><h2>6. International transfers</h2><p>Some of our service providers operate outside the United Kingdom. Where data is transferred internationally, we ensure appropriate safeguards are in place, including Standard Contractual Clauses approved by the ICO.</p></section>
    <section className="lS"><h2>7. Data retention</h2><p>We retain your account data for as long as your account is active. Conversation data is retained for 12 months to improve Laura's safety and quality, then automatically deleted. If you delete your account, all associated data is removed within 30 days. Credit transaction records are retained for 6 years for tax and accounting purposes as required by UK law.</p></section>
    <section className="lS"><h2>8. Your rights under UK GDPR</h2><p>You have the right to access your personal data and receive a copy in a portable format (data subject access request). You have the right to correct inaccurate information. You have the right to request deletion of your data (right to be forgotten). You have the right to restrict or object to certain processing. You have the right to withdraw consent at any time. To exercise any of these rights, email notice@omela.ai. We will respond within 30 days as required by UK GDPR.</p></section>
    <section className="lS"><h2>9. Security</h2><p>We implement appropriate technical and organisational measures to protect your data: encryption in transit (TLS) and at rest (AES-256 for sensitive fields), access controls, rate limiting, input validation, regular security audits, and dependency scanning. No system is perfectly secure, but we take proportionate steps to protect your information.</p></section>
    <section className="lS"><h2>10. Cookies</h2><p>We use essential cookies for authentication and site functionality. We do not use advertising or tracking cookies. If we introduce analytics cookies in future, we will request your consent first.</p></section>
    <section className="lS"><h2>11. Children</h2><p>Laura is not intended for use by individuals under 16 without parental or guardian supervision. We do not knowingly collect data from children under 16.</p></section>
    <section className="lS"><h2>12. Complaints</h2><p>If you are unhappy with how we handle your data, you have the right to lodge a complaint with the Information Commissioner's Office (ICO). Website: ico.org.uk. Phone: 0303 123 1113.</p></section>
    <section className="lS"><h2>13. Changes</h2><p>We may update this notice from time to time. Significant changes will be communicated by email. The latest version will always be available on this page.</p></section>
    <section className="lS" style={{borderBottom:"none"}}><h2>14. Contact</h2><p>For questions about this privacy notice or your data, email <a href="mailto:notice@omela.ai" className="lLk">notice@omela.ai</a>.</p></section>
  </div></main>
  <footer className="lFt"><div className="cnt lFtI"><p>&copy; 2026 Omela</p><div className="lFtLks"><Link href="/terms" className="lFtL">Terms</Link><Link href="/status" className="lFtL">Status</Link></div></div></footer>
</div></>);}
const CSS=`
*{box-sizing:border-box;margin:0;padding:0}body{background:${c.bg};color:${c.text};font-family:'DM Sans',-apple-system,sans-serif;-webkit-font-smoothing:antialiased;font-size:16px}a{color:inherit;text-decoration:none}
.serif{font-family:'Instrument Serif',Georgia,serif}.cnt{max-width:680px;margin:0 auto;padding:0 20px}
.lW{min-height:100vh;display:flex;flex-direction:column}.lN{border-bottom:1px solid ${c.border};background:rgba(248,246,241,0.94);backdrop-filter:blur(16px);position:sticky;top:0;z-index:10}.lNI{display:flex;align-items:center;justify-content:space-between;height:56px}.lBr{display:flex;align-items:center;gap:7px;font-size:14px;font-weight:800}.lLo{width:26px;height:26px;border-radius:8px;overflow:hidden}.lBrN{letter-spacing:-0.03em}.lBk{display:flex;align-items:center;gap:4px;font-size:13px;font-weight:600;color:${c.muted}}
.lM{flex:1;padding:48px 0 64px}.lUp{font-size:12px;color:${c.muted};font-weight:600;margin-bottom:8px}.lTi{font-size:clamp(32px,7vw,48px);letter-spacing:-0.04em;line-height:1.06}.lIn{margin-top:16px;font-size:15px;line-height:1.75;color:${c.sub};padding-bottom:20px;border-bottom:1px solid ${c.border}}
.lBadges{display:flex;gap:8px;margin-top:14px;margin-bottom:6px;flex-wrap:wrap}.lBadge{padding:5px 12px;border-radius:8px;background:rgba(37,99,235,0.06);border:1px solid rgba(37,99,235,0.1);color:${c.accent};font-size:11px;font-weight:700}
.lS{padding:22px 0;border-bottom:1px solid ${c.border}}.lS h2{font-size:16px;font-weight:800;letter-spacing:-0.02em;margin-bottom:8px}.lS p{font-size:14px;line-height:1.78;color:${c.sub}}.lLk{color:${c.accent};font-weight:600;text-decoration:underline;text-underline-offset:2px}
.lFt{border-top:1px solid ${c.border};padding:16px 0}.lFtI{display:flex;align-items:center;justify-content:space-between}.lFtI p{font-size:11px;color:${c.muted}}.lFtLks{display:flex;gap:12px}.lFtL{font-size:11px;color:${c.muted};font-weight:600}
@media(min-width:640px){.cnt{padding:0 28px}}
`;
