"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState, useCallback, type ReactNode } from "react";
import { AnimatePresence, motion, useInView } from "framer-motion";
import { ArrowRight, Mic, ChevronLeft, ChevronRight, Search, FileCheck, Languages, Users, Building2, Code2, Shield, MessageSquare, Globe2, Stethoscope, Smartphone, Copy, Check, Share2 } from "lucide-react";

const FONT = `@import url('https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;0,9..40,600;0,9..40,700;0,9..40,800;1,9..40,400&display=swap');`;
const c = { bg:"#F8F6F1",card:"#fff",dark:"#08090C",text:"#111214",sub:"#4A4F5C",muted:"#888E9C",accent:"#2563EB",accentSoft:"#ECF2FF",border:"#E3DDD2",borderDk:"#222633",green:"#22C55E",greenSoft:"#ECFDF3",greenDk:"#15803D",warm:"#C9956B",warmSoft:"#FFF8F0" };
type Role="patient"|"provider"|"developer";

function FI({children,delay=0,className=""}:{children:ReactNode;delay?:number;className?:string}){const ref=useRef<HTMLDivElement>(null);const v=useInView(ref,{once:true,amount:0.05});return<motion.div ref={ref} initial={{opacity:0,y:18}} animate={v?{opacity:1,y:0}:{}} transition={{duration:0.6,delay,ease:[0.22,1,0.36,1]}} className={className}>{children}</motion.div>;}
function Soon(){return<span className="soon">Coming soon</span>;}
function Chk({dark=false}:{dark?:boolean}){return<motion.span initial={{scale:0}} whileInView={{scale:1}} viewport={{once:true}} transition={{type:"spring",stiffness:500,damping:18}} className={`chk${dark?" chkD":""}`}>&#10003;</motion.span>;}

function Typewriter(){const lines=useMemo(()=>["You sit on hold for 45 minutes.","You chase prescriptions for days.","You get a letter you do not understand.","You move cities with no doctor."],[]);const[li,setLi]=useState(0);const[ci,setCi]=useState(0);const[del,setDel]=useState(false);const[pause,setPause]=useState(false);useEffect(()=>{if(pause){const t=setTimeout(()=>{setPause(false);setDel(true);},1400);return()=>clearTimeout(t);}const cur=lines[li];if(!del){if(ci<cur.length){const t=setTimeout(()=>setCi(p=>p+1),28);return()=>clearTimeout(t);}else setPause(true);}else{if(ci>0){const t=setTimeout(()=>setCi(p=>p-1),14);return()=>clearTimeout(t);}else{setDel(false);setLi(p=>(p+1)%lines.length);}}},[li,ci,del,pause,lines]);return<span className="tw">{lines[li].slice(0,ci)}<span className="twC">|</span></span>;}

function StatusBar(){return<div className="stBar"><div className="container stIn"><motion.span animate={{scale:[1,1.3,1]}} transition={{duration:2,repeat:Infinity}} className="stDot"/><span className="stLbl">All systems operational</span><Link href="/status" className="stLnk">View status</Link></div></div>;}

const convos=[{lang:"English",flag:"\u{1F1EC}\u{1F1E7}",msgs:[{f:"u",t:"I just moved to Manchester and need to register with a GP."},{f:"l",t:"I will find practices near you. What is your postcode?"},{f:"u",t:"M1, near Piccadilly."},{f:"l",t:"Found 3 practices near M1."},{f:"a",t:"City Health Centre \u00b7 0.3mi \u00b7 Accepting patients"},{f:"l",t:"I have prepared a registration callback request for you."},{f:"a",t:"Callback request prepared \u00b7 Ready to review"}]},{lang:"Fran\u00e7ais",flag:"\u{1F1EB}\u{1F1F7}",msgs:[{f:"u",t:"J'ai besoin de renouveler mon ordonnance."},{f:"l",t:"Combien de jours de stock vous reste-t-il?"},{f:"u",t:"Environ 3 jours."},{f:"l",t:"J'ai prepare une demande de renouvellement."},{f:"a",t:"Demande preparee \u00b7 Rappel dans 25 jours"},{f:"l",t:"Je vous rappellerai 5 jours avant la fin."}]},{lang:"Yor\u00f9b\u00e1",flag:"\u{1F1F3}\u{1F1EC}",msgs:[{f:"u",t:"Mo ni iba ati efori lati ana. Mo wa ni HD1."},{f:"l",t:"Mo ti ri ile-iwosan meji nitosi re."},{f:"a",t:"Spring Street Surgery \u00b7 0.4 maili"},{f:"l",t:"Se o fe ki n ran o lowo lati mura ibeere?"},{f:"u",t:"Beeni, e seun."},{f:"a",t:"Ibeere ipe-pada ti setan"}]}];

function PhoneMockup(){const[li,setLi]=useState(0);const[vi,setVi]=useState(0);const[typing,setTyping]=useState(false);const cv=convos[li];useEffect(()=>{if(vi>=cv.msgs.length){const t=setTimeout(()=>{setLi(p=>(p+1)%convos.length);setVi(0);},2400);return()=>clearTimeout(t);}const msg=cv.msgs[vi];if(msg.f==="u"){setVi(p=>p+1);}else{setTyping(true);const t=setTimeout(()=>{setTyping(false);setVi(p=>p+1);},400+Math.random()*400);return()=>clearTimeout(t);}},[vi,li,cv.msgs]);return(<div className="phW"><motion.div className="phGlow" animate={{opacity:[0.12,0.3,0.12]}} transition={{duration:5,repeat:Infinity}}/><motion.div className="phF" initial={{opacity:0,y:16}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><div className="phB"><div className="phDI"/><div className="phS"><div className="phH"><div className="phAv"><Image src="/laura-avatar.png" alt="Laura" fill sizes="22px" style={{objectFit:"cover"}}/></div><div><div className="phN">Laura <svg width="10" height="10" viewBox="0 0 24 24" fill="none"><path d="M12 1L14.9 3.6L18.6 3.2L19.4 6.8L22.5 8.7L21.2 12.2L22.5 15.7L19.4 17.6L18.6 21.2L14.9 20.8L12 23.4L9.1 20.8L5.4 21.2L4.6 17.6L1.5 15.7L2.8 12.2L1.5 8.7L4.6 6.8L5.4 3.2L9.1 3.6L12 1Z" fill="#22C55E"/><path d="M8.5 12.5L10.5 14.5L15.5 9.5" stroke="#fff" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg></div><div className="phOn"><span className="phOnD"/>online</div></div></div><AnimatePresence mode="wait"><motion.div key={li} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="phLang">{cv.flag} {cv.lang}</motion.div></AnimatePresence><div className="phBdy">{cv.msgs.slice(0,vi).map((msg,i)=>(<motion.div key={`${li}-${i}`} initial={{opacity:0,y:3}} animate={{opacity:1,y:0}} className={`phR ${msg.f==="u"?"phRR":"phRL"}`}>{msg.f==="a"?<div className="phAct">{msg.t}</div>:<div className={`phBb ${msg.f==="u"?"phBbU":"phBbL"}`}>{msg.t}{msg.f==="u"&&<span className="phMt"><svg width="10" height="7" viewBox="0 0 20 14" fill="none"><path d="M1.5 7.6L4.7 10.8L10.2 5.2" stroke="#53BDEB" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/><path d="M7.3 7.6L10.5 10.8L18.2 3.2" stroke="#53BDEB" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/></svg></span>}</div>}</motion.div>))}{typing&&<div className="phR phRL"><div className="phBb phBbL phTy"><span/><span/><span/></div></div>}</div><div className="phCo"><div className="phCoF"><span className="phCoT">Message</span></div><div className="phCoM"><Mic size={10} color="#fff"/></div></div></div></div></motion.div></div>);}

/* ─── Canvas Globe ─── */
const gs=[{country:"United Kingdom",flag:"\u{1F1EC}\u{1F1E7}",name:"Sarah, 34, Leeds",quote:"I called at 8:01am. Busy. By 8:15 all slots were gone. Three weeks of this.",laura:"Laura prepares a structured callback request so the practice can respond more efficiently.",lat:54,lng:-1.5},{country:"United States",flag:"\u{1F1FA}\u{1F1F8}",name:"Marcus, 28, Chicago",quote:"I delayed seeing a doctor for six months because I was terrified of the cost.",laura:"Laura surfaces lower-cost options and community clinics near you automatically.",lat:41.8,lng:-87.6},{country:"Nigeria",flag:"\u{1F1F3}\u{1F1EC}",name:"Amina, 41, Lagos",quote:"Four doctors for ten thousand people. I spent two days trying to find someone.",laura:"Laura searches provider availability in real time and helps route you to whoever can see you soonest.",lat:6.5,lng:3.4},{country:"India",flag:"\u{1F1EE}\u{1F1F3}",name:"Priya, 55, Jaipur",quote:"My mother lives two hours from the nearest clinic. She never knows when to worry.",laura:"Laura helps assess urgency remotely and tells you whether to travel now or monitor at home.",lat:26.9,lng:75.8},{country:"Brazil",flag:"\u{1F1E7}\u{1F1F7}",name:"Lucas, 23, London",quote:"I moved to London and could not explain my symptoms in English.",laura:"Laura captures symptoms in your language, generates a structured bilingual note, and helps you share it before you arrive.",lat:51.5,lng:-0.1}];

function latLngToXYZ(lat:number,lng:number){const phi=(90-lat)*(Math.PI/180);const theta=(lng+180)*(Math.PI/180);return{x:-Math.sin(phi)*Math.cos(theta),y:Math.cos(phi),z:Math.sin(phi)*Math.sin(theta)};}

function CanvasGlobe({active}:{active:number}){
  const canvasRef=useRef<HTMLCanvasElement>(null);const rotRef=useRef(0.4);const frameRef=useRef(0);
  useEffect(()=>{
    const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext("2d");if(!ctx)return;
    const dpr=window.devicePixelRatio||1;
    function resize(){if(!canvas)return;const rect=canvas.getBoundingClientRect();canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;}
    resize();
    const N=300;const golden=Math.PI*(3-Math.sqrt(5));const dots:{x:number;y:number;z:number}[]=[];
    for(let i=0;i<N;i++){const theta=golden*i;const phi=Math.acos(1-2*(i+0.5)/N);dots.push({x:Math.cos(theta)*Math.sin(phi),y:Math.cos(phi),z:Math.sin(theta)*Math.sin(phi)});}
    const cityXYZ=gs.map(g=>latLngToXYZ(g.lat,g.lng));
    function draw(){
      if(!canvas||!ctx)return;
      const w=canvas.width/dpr;const h=canvas.height/dpr;const R=Math.min(w,h)*0.42;const cx=w/2;const cy=h/2;
      const rot=rotRef.current;const cosR=Math.cos(rot);const sinR=Math.sin(rot);
      ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);
      // Glow
      const glow=ctx.createRadialGradient(cx-R*0.2,cy-R*0.2,0,cx,cy,R*1.3);
      glow.addColorStop(0,"rgba(201,149,107,0.07)");glow.addColorStop(0.6,"rgba(201,149,107,0.02)");glow.addColorStop(1,"transparent");
      ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);
      // Outline
      ctx.beginPath();ctx.arc(cx,cy,R,0,Math.PI*2);ctx.strokeStyle="rgba(192,184,164,0.25)";ctx.lineWidth=0.8;ctx.stroke();
      // Inner fill
      const sg=ctx.createRadialGradient(cx-R*0.25,cy-R*0.25,R*0.1,cx,cy,R);
      sg.addColorStop(0,"rgba(248,246,241,0.06)");sg.addColorStop(1,"rgba(224,218,200,0.03)");
      ctx.fillStyle=sg;ctx.beginPath();ctx.arc(cx,cy,R,0,Math.PI*2);ctx.fill();
      // Grid
      ctx.strokeStyle="rgba(200,192,172,0.07)";ctx.lineWidth=0.5;
      for(let lat=-60;lat<=60;lat+=30){const p=(90-lat)*Math.PI/180;const rr=Math.sin(p)*R;const ry=cy-Math.cos(p)*R;ctx.beginPath();ctx.ellipse(cx,ry,rr,rr*0.12,0,0,Math.PI*2);ctx.stroke();}
      // Dots
      for(const p of dots){const x=p.x*cosR+p.z*sinR;const z=-p.x*sinR+p.z*cosR;const y=p.y;if(z<-0.05)continue;const sx=cx+x*R;const sy=cy-y*R;const alpha=Math.max(0,Math.min(1,(z+0.3)*0.6));const sz=1+z*0.8;ctx.beginPath();ctx.arc(sx,sy,sz,0,Math.PI*2);ctx.fillStyle=`rgba(180,168,148,${alpha*0.55})`;ctx.fill();}
      // Cities
      const projected:{sx:number;sy:number;z:number}[]=[];
      for(let i=0;i<cityXYZ.length;i++){const p=cityXYZ[i];const x=p.x*cosR+p.z*sinR;const z=-p.x*sinR+p.z*cosR;const y=p.y;const sx=cx+x*R;const sy=cy-y*R;projected.push({sx,sy,z});if(z<0)continue;
        if(i===active){ctx.beginPath();ctx.arc(sx,sy,8,0,Math.PI*2);ctx.fillStyle="rgba(201,149,107,0.15)";ctx.fill();ctx.beginPath();ctx.arc(sx,sy,14,0,Math.PI*2);ctx.fillStyle="rgba(201,149,107,0.06)";ctx.fill();}
        ctx.beginPath();ctx.arc(sx,sy,i===active?4:2.5,0,Math.PI*2);ctx.fillStyle=i===active?c.warm:"rgba(176,168,148,0.7)";ctx.fill();}
      // Arcs
      for(let i=0;i<cityXYZ.length;i++){const next=(i+1)%cityXYZ.length;const a=projected[i];const b=projected[next];if(a.z<-0.2||b.z<-0.2)continue;const mx=(a.sx+b.sx)/2;const my=(a.sy+b.sy)/2-Math.abs(a.sx-b.sx)*0.2;ctx.beginPath();ctx.moveTo(a.sx,a.sy);ctx.quadraticCurveTo(mx,my,b.sx,b.sy);ctx.strokeStyle=i===active?"rgba(201,149,107,0.35)":"rgba(201,149,107,0.06)";ctx.lineWidth=i===active?1.2:0.5;ctx.setLineDash(i===active?[4,3]:[]);ctx.stroke();ctx.setLineDash([]);}
      rotRef.current+=0.002;frameRef.current=requestAnimationFrame(draw);
    }
    frameRef.current=requestAnimationFrame(draw);
    const ro=new ResizeObserver(()=>{resize();});ro.observe(canvas);
    return()=>{cancelAnimationFrame(frameRef.current);ro.disconnect();};
  },[active]);
  return<canvas ref={canvasRef} className="globeCanvas"/>;
}

function GlobeSection(){const[a,setA]=useState(0);const tr=useRef<ReturnType<typeof setTimeout>|null>(null);const reset=useCallback(()=>{if(tr.current)clearTimeout(tr.current);tr.current=setTimeout(()=>setA(p=>(p+1)%gs.length),6000);},[]);useEffect(()=>{reset();return()=>{if(tr.current)clearTimeout(tr.current);};},[a,reset]);const s=gs[a];return(
<section className="globeSec"><div className="container"><FI><div className="shW"><h2 className="serif shT">How people struggle to reach care.</h2></div></FI><div className="globeW"><div className="globeV"><CanvasGlobe active={a}/></div><div className="globeC"><AnimatePresence mode="wait"><motion.div key={a} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-6}} transition={{duration:0.3}} className="globeStory"><div className="globeCtry"><span style={{fontSize:"18px"}}>{s.flag}</span><span className="globeCtryN">{s.country}</span></div><p className="serif globeQ">&ldquo;{s.quote}&rdquo;</p><p className="globeNm">{s.name}</p><div className="globeL"><div className="globeLA"><Image src="/laura-avatar.png" alt="Laura" fill sizes="22px" style={{objectFit:"cover"}}/></div><p className="globeLT">{s.laura}</p></div></motion.div></AnimatePresence><div className="globeNav"><div className="globeDs">{gs.map((_,i)=><button key={i} className={`globeD${i===a?" globeDA":""}`} onClick={()=>setA(i)}/>)}</div><div className="globeAs"><button className="globeA" onClick={()=>setA(p=>(p-1+5)%5)}><ChevronLeft size={15}/></button><button className="globeA" onClick={()=>setA(p=>(p+1)%5)}><ChevronRight size={15}/></button></div></div></div></div></div></section>);}

/* ─── Terminal (FIXED HEIGHT) ─── */
function SDKTerminal(){const lines=useMemo(()=>['$ npm install @omela/laura-sdk','','  import { Laura } from "@omela/laura-sdk";','','  const laura = new Laura({','    apiKey: process.env.OMELA_KEY,','    region: "eu-west-2"','  });','','  const session = await laura.navigate({','    userId: "patient_4102",','    lang: "fr",','    concern: "prescription renewal"','  });','','  // Laura found 2 practices, drafted request','  Done in 1.1s'],[]);const[vl,setVl]=useState(0);const[ci,setCi]=useState(0);useEffect(()=>{if(vl>=lines.length){const t=setTimeout(()=>{setVl(0);setCi(0);},3000);return()=>clearTimeout(t);}const line=lines[vl];if(ci<line.length){const t=setTimeout(()=>setCi(p=>p+1),line.startsWith("  //")?36:18);return()=>clearTimeout(t);}else{const t=setTimeout(()=>{setVl(p=>p+1);setCi(0);},line===""?50:140);return()=>clearTimeout(t);}},[vl,ci,lines]);return<div className="trm"><div className="trmT"><div className="trmD"><span/><span/><span/></div><span className="trmTi">Laura SDK</span><Soon/></div><div className="trmB">{lines.slice(0,vl+1).map((line,i)=>{const a2=i===vl;return<div key={i} className="trmL" style={{color:line.startsWith("  Done")||line.startsWith("  //")?"#4ADE80":line.startsWith("$")?"#E2E8F0":"#94A3B8"}}>{a2?line.slice(0,ci):line}{a2&&<span className="trmC">|</span>}</div>;})}</div></div>;}

/* ─── Roadmap (dark swipeable) ─── */
const roadmapItems=[{title:"GP request routing",desc:"Laura will help submit callback and prescription requests directly through supported practice channels.",stage:"Stage 2",emoji:"\u{1F4E8}"},{title:"Practice portal",desc:"A dashboard for care teams to manage structured intake, urgency triage, and patient routing.",stage:"Stage 2",emoji:"\u{1F3E5}"},{title:"WhatsApp access",desc:"Reach Laura through WhatsApp for an even simpler, mobile-first care navigation experience.",stage:"Stage 2",emoji:"\u{1F4F1}"},{title:"Multilingual notes",desc:"Full 40+ language support with bilingual structured notes for the practice.",stage:"Stage 2",emoji:"\u{1F30D}"},{title:"Telehealth pathways",desc:"Laura connects you to telehealth consultations where in-person visits are not practical.",stage:"Stage 3",emoji:"\u{1FA7A}"}];

function RoadmapCards(){return(<section className="sec"><div className="container"><FI><div className="shW"><h2 className="serif shT">Where Laura is going.</h2><p className="shB">We are starting with care navigation first. Here is what comes next.</p></div></FI><div className="roadScroll">{roadmapItems.map((item,i)=>(<motion.div key={item.title} className="roadCard" initial={{opacity:0,y:14}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*0.08}}><div className="roadTop"><motion.span className="roadEmoji" animate={{y:[0,-3,0],rotate:[0,5,-5,0]}} transition={{duration:3+i*0.3,repeat:Infinity,ease:"easeInOut"}}>{item.emoji}</motion.span><motion.span className="roadSt" animate={{scale:[1,1.05,1]}} transition={{duration:2,repeat:Infinity,delay:i*0.4}}>{item.stage}</motion.span></div><h4 className="roadTi">{item.title}</h4><p className="roadDs">{item.desc}</p><div className="roadLine"/></motion.div>))}</div><FI delay={0.3}><p className="roadNote">Laura currently works through the website. WhatsApp and other access channels are part of the roadmap.</p></FI></div></section>);}

/* ─── Infra Logos ─── */
const infraLogos=[{name:"Vercel",src:"/logos/vercel.png"},{name:"Neon",src:"/logos/neon.png"},{name:"Stripe",src:"/logos/stripe.png"},{name:"OpenAI",src:"/logos/openai.png"},{name:"PostgreSQL",src:"/logos/postgres.png"},{name:"Twilio",src:"/logos/twilio.png"}];
function InfraSection(){return(<section className="infraSec"><div className="container"><FI><div className="infraIn"><p className="infraLbl">Built on modern infrastructure</p><div className="infraGrid">{infraLogos.map(logo=>(<div key={logo.name} className="infraItem"><div className="infraLogo"><Image src={logo.src} alt={logo.name} width={100} height={32} style={{objectFit:"contain",width:"100%",height:"100%",filter:"grayscale(1) opacity(0.5)"}}/></div></div>))}</div></div></FI></div></section>);}

/* ─── Confetti ─── */
function Confetti(){const particles=useMemo(()=>Array.from({length:20},(_,i)=>({id:i,emoji:["\u{1F389}","\u{2728}","\u{1F38A}","\u{1F31F}","\u{1F4AB}"][i%5],left:Math.random()*100,delay:Math.random()*0.6,duration:1.5+Math.random()*1,rotate:Math.random()*360})),[]);return<div className="confW">{particles.map(p=><motion.span key={p.id} className="confP" initial={{opacity:1,y:0,scale:0}} animate={{opacity:[1,1,0],y:-120,scale:[0,1.2,0.8],rotate:p.rotate}} transition={{duration:p.duration,delay:p.delay,ease:"easeOut"}} style={{left:`${p.left}%`}}>{p.emoji}</motion.span>)}</div>;}

/* ─── Modal ─── */
function SuccessModal({open,onClose,referralCode}:{open:boolean;onClose:()=>void;referralCode:string}){
  const[copied,setCopied]=useState(false);const link=typeof window!=="undefined"?`${window.location.origin}?ref=${referralCode}`:"";
  function copyLink(){navigator.clipboard.writeText(link).then(()=>{setCopied(true);setTimeout(()=>setCopied(false),2000);});}
  async function shareLink(){if(navigator.share){try{await navigator.share({title:"Join Omela",text:"Skip the GP queue. Laura helps you navigate healthcare.",url:link});}catch{}}else{copyLink();}}
  return<AnimatePresence>{open&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={onClose} className="modO"><motion.div initial={{opacity:0,y:20,scale:0.95}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:10}} transition={{type:"spring",damping:20,stiffness:300}} onClick={e=>e.stopPropagation()} className="modB"><Confetti/><motion.div className="modCel" initial={{scale:0}} animate={{scale:1}} transition={{type:"spring",delay:0.2,stiffness:400,damping:15}}><span className="modCelE">{"\u{1F389}"}</span></motion.div><h3 className="serif modTi">You are on the list!</h3><p className="modBd">Laura will reach out as access opens. Invite 3 friends to move up the waitlist and unlock bonus credits.</p>{referralCode&&<div className="modRef"><p className="modRefLbl">Your referral link</p><div className="modRefBox"><span className="modRefUrl">{link.replace("https://","").replace("http://","")}</span><button onClick={copyLink} className="modRefCp" type="button">{copied?<Check size={14}/>:<Copy size={14}/>}</button></div><div className="modRefBts"><button onClick={shareLink} className="btnP modShareBtn" type="button"><Share2 size={13}/>Share link</button><a href="https://x.com/joinomela" target="_blank" rel="noreferrer" className="btnS modXBtn">Follow @joinomela</a></div></div>}<button type="button" className="modClose" onClick={onClose}>Close</button></motion.div></motion.div>}</AnimatePresence>;}

/* ═══════════════════════════════════════════════════════════════ */
export default function Page(){
  const[role,setRole]=useState<Role>("patient");const[email,setEmail]=useState("");const[website,setWebsite]=useState("");const[agreed,setAgreed]=useState(false);const[submitting,setSubmitting]=useState(false);const[success,setSuccess]=useState("");const[error,setError]=useState("");const[modalOpen,setModalOpen]=useState(false);const[referralCode,setReferralCode]=useState("");const[refParam,setRefParam]=useState("");
  useEffect(()=>{if(typeof window!=="undefined"){const params=new URLSearchParams(window.location.search);const ref=params.get("ref");if(ref)setRefParam(ref);}},[]);
  async function handleSubmit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!agreed)return;setSubmitting(true);setSuccess("");setError("");try{const res=await fetch("/api/waitlist",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,role,website,source:"landing-page",marketingOptIn:false,ref:refParam||undefined})});const data=await res.json();if(!res.ok){if(data.referralCode)setReferralCode(data.referralCode);setError(data.error||"Something went wrong.");return;}setSuccess(data.message||"You are in.");if(data.referralCode)setReferralCode(data.referralCode);setEmail("");setRole("patient");setWebsite("");setAgreed(false);setModalOpen(true);}catch{setError("Something went wrong.");}finally{setSubmitting(false);}}

  return(<><style>{FONT}</style><style>{CSS}</style>
    <SuccessModal open={modalOpen} onClose={()=>setModalOpen(false)} referralCode={referralCode}/>
    <div className="wrap">
      <StatusBar/>
      <motion.nav initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} className="nav"><div className="container navR"><Link href="/" className="navBr"><div className="navLo"><Image src="/omela-logo-mark.png" alt="Omela" width={34} height={34} style={{width:"100%",height:"100%",objectFit:"contain"}}/></div><div><div className="navNm">Omela</div><div className="navSb">POWERED BY LAURA</div></div></Link><div className="navLks"><a href="#how" className="navLk">How it works</a><a href="#pricing" className="navLk">Pricing</a><Link href="/how-laura-helps" className="navLk">Use cases</Link></div><a href="#waitlist" className="btnP navCt">Join waitlist <ArrowRight size={13}/></a></div></motion.nav>

      <section className="heroSec"><div className="container"><div className="heroTxt"><FI><h1 className="serif heroTi">Getting care<br/><span className="heroAc">should not be this hard.</span></h1></FI><FI delay={0.05}><div className="heroBd"><Typewriter/></div></FI><FI delay={0.1}><p className="heroSub">Laura is a care navigation platform that helps people find doctors, prepare prescription requests, understand referral letters, and generate bilingual notes for the practice. She does not just answer questions. She helps move care access forward.</p></FI><FI delay={0.14}><div className="heroBt"><Link href="/demo" className="btnP">See Laura in action <ArrowRight size={14}/></Link><a href="#waitlist" className="btnS">Join waitlist</a></div></FI></div><div className="heroPh"><PhoneMockup/></div></div></section>

      <section id="how" className="sec"><div className="container"><FI><div className="shW"><h2 className="serif shT">Laura does not just answer health questions.<br/>She helps get the admin moving.</h2></div></FI><div className="capGrid">{[{icon:<Search size={22}/>,title:"Finds doctors and helps prepare requests",body:"Laura searches practices near you, surfaces suitable options, and helps prepare registration or callback requests for submission with your approval."},{icon:<FileCheck size={22}/>,title:"Drafts prescriptions and tracks refills",body:"Laura prepares your repeat prescription request, helps you send it through the available channel, and reminds you before you run out."},{icon:<Languages size={22}/>,title:"Generates structured bilingual notes",body:"Laura captures your symptoms in your language and turns them into a structured bilingual note you can share with the practice."}].map((item,i)=>(<FI key={item.title} delay={i*0.07}><div className="capCard"><motion.div className="capIc" animate={{y:[0,-4,0]}} transition={{duration:3+i*0.5,repeat:Infinity,ease:"easeInOut"}}>{item.icon}</motion.div><h3 className="capTi">{item.title}</h3><p className="capBd">{item.body}</p></div></FI>))}</div><FI delay={0.2}><div style={{textAlign:"center",marginTop:"28px"}}><Link href="/how-laura-helps" className="seeAll">See all care scenarios <ArrowRight size={14}/></Link></div></FI></div></section>

      <section className="sec" style={{paddingTop:0}}><div className="container"><FI><div className="shW"><h2 className="serif shT">A chatbot answers questions.<br/>Laura helps move care access forward.</h2></div></FI><FI><div className="baGrid"><div className="baCard baBf"><h3 className="baTi">Without Laura</h3>{["You call the GP. Busy signal. Try again tomorrow.","You email the pharmacy. No reply for three days.","You get a referral full of medical jargon with no guidance.","You arrive in a new city with zero medical contacts.","You try to explain symptoms in a language that is not yours."].map(item=><div key={item} className="baIt"><span className="baX">&#10007;</span>{item}</div>)}</div><div className="baCard baAf"><h3 className="baTi">With Laura</h3>{["Laura prepares a structured callback request and helps route it through the available channel.","Laura drafts your refill request and helps submit it where supported.","Laura translates your referral into plain language with appointment prep.","Laura finds nearby accepting practices and helps prepare the registration request.","Laura prepares a bilingual note for the practice that you can review and share."].map(item=><div key={item} className="baIt"><Chk/><span>{item}</span></div>)}</div></div></FI></div></section>

      <GlobeSection/>

      <section className="sec"><div className="container"><FI><div className="shW"><h2 className="serif shT">Who Laura is for.</h2></div></FI><div className="audGrid">{[{icon:<Users size={22}/>,title:"People",desc:"Laura helps act on your behalf. She finds nearby practices, drafts your prescription request, explains your hospital letter, and helps prepare your callback request. You spend less time chasing the system.",color:c.accent},{icon:<Building2 size={22}/>,title:"Care teams",desc:"Laura intercepts and structures incoming patient demand before it hits reception. She helps assess urgency, captures symptoms in structured format, and helps route the next step.",color:c.green},{icon:<Code2 size={22}/>,title:"Developers",desc:"Embed Laura's care-navigation engine into your product via API. Provider search, urgency assessment, prescription routing, and multilingual intake.",color:c.warm,soon:true}].map((item,i)=>(<FI key={item.title} delay={i*0.07}><div className="audCard"><motion.div className="audIc" style={{background:`${item.color}10`,color:item.color}} animate={{rotate:[0,3,-3,0]}} transition={{duration:4+i,repeat:Infinity,ease:"easeInOut"}}>{item.icon}</motion.div><div style={{display:"flex",alignItems:"center",gap:"6px"}}><h3 className="audTi">{item.title}</h3>{item.soon&&<Soon/>}</div><p className="audBd">{item.desc}</p></div></FI>))}</div></div></section>

      <section className="sec" style={{paddingTop:0}}><div className="container"><FI><div className="glC"><div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:"8px",flexWrap:"wrap"}}><h2 className="serif glT">Laura speaks your language.</h2><Soon/></div><p className="glB">40+ languages. Laura responds in the language you start with and generates structured bilingual notes for the practice.</p><div className="glF">{["\u{1F1EC}\u{1F1E7} UK","\u{1F1FA}\u{1F1F8} US","\u{1F1EB}\u{1F1F7} France","\u{1F1F3}\u{1F1EC} Nigeria","\u{1F1EE}\u{1F1F3} India","\u{1F30D} 40+ more"].map(f=><span key={f} className="glFi">{f}</span>)}</div></div></FI></div></section>

      <section className="secDk"><div className="container"><FI><div className="shW"><h2 className="serif shT" style={{color:"#fff"}}>Build with Laura.</h2><p className="shB" style={{color:"rgba(255,255,255,0.5)"}}>Embed care navigation, provider routing, and multilingual intake into your product.</p></div></FI><div className="g2" style={{marginTop:"32px"}}><FI><SDKTerminal/></FI><FI delay={0.08}><div className="dkC"><h3 className="dkCT">Infrastructure for health apps</h3><p className="dkCB">Add Laura to patient portals, telehealth platforms, or internal tooling.</p><div className="ftL" style={{marginTop:"16px"}}>{["Provider search and availability API","Urgency assessment engine","Prescription and callback routing","Multilingual intake with bilingual notes"].map(f=><div key={f} className="ftR" style={{color:"rgba(255,255,255,0.7)"}}><Chk dark/><span>{f}</span></div>)}</div></div></FI></div></div></section>

      <RoadmapCards/>
      <InfraSection/>

      <section id="pricing" className="secPr"><div className="container"><FI><div className="shW"><h2 className="serif shT">Credits-based pricing.</h2><p className="shB">Every action Laura takes uses credits. Start free. Pay as you grow.</p></div></FI><div className="prGrid">{[{name:"People",price:"50 free credits",period:"then \u00a34.99 / 200 credits",desc:"For individuals navigating the healthcare system.",features:["Find nearby GP practices","Prepare callback requests","Draft repeat prescriptions","Explain referral letters","Urgency guidance","Bilingual note generation"],cta:"Join waitlist",hl:false},{name:"Care Teams",price:"From \u00a32,500",period:"/month",desc:"For GP practices, clinics, and care organisations managing patient demand at scale.",features:["Structured patient intake","Urgency assessment and routing","Multilingual access for patients","Callback and request management","Demand analytics dashboard","Dedicated onboarding support"],cta:"Request demo",hl:true,badge:"Best for practices"},{name:"Developer",price:"Custom",period:"usage-based",desc:"For health platforms, patient portals, and telehealth apps embedding Laura's engine via API.",features:["Full REST API access","Provider search endpoints","Urgency assessment engine","Prescription routing API","Multilingual intake pipeline","Sandbox environment","Priority engineering support"],cta:"Talk to us",hl:false,soon:true}].map((p,i)=>(<FI key={p.name} delay={i*0.06}><div className={`prCard${p.hl?" prCardDk":""}`}>{p.badge&&<div className="prBg">{p.badge}</div>}<div style={{display:"flex",alignItems:"center",gap:"6px"}}><span className="prNm">{p.name}</span>{p.soon&&<Soon/>}</div><div className="prPr"><span className="serif prAmt">{p.price}</span></div><p className="prPd2">{p.period}</p><p className="prDs">{p.desc}</p><div className="prFts">{p.features.map(f=><div key={f} className="prFt"><Chk dark={p.hl}/><span>{f}</span></div>)}</div><a href="#waitlist" className={`btnP prBt${p.hl?" prBtW":""}`}>{p.cta}</a></div></FI>))}</div></div></section>

      <section id="waitlist" className="sec"><div className="container"><FI><div className="wlC"><div className="shW"><h2 className="serif shT">Join the waitlist.</h2><p className="shB">We are onboarding in batches. Early members receive 50 free credits.</p></div><form className="wlF" onSubmit={handleSubmit}><input className="inp" type="email" placeholder="Your email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/><select className="inp" value={role} onChange={e=>setRole(e.target.value as Role)}><option value="patient">I need care access</option><option value="provider">I run a practice</option><option value="developer">I am a developer</option></select><input type="text" name="website" value={website} onChange={e=>setWebsite(e.target.value)} tabIndex={-1} autoComplete="off" aria-hidden="true" style={{position:"absolute",left:"-9999px",opacity:0,pointerEvents:"none",height:0,width:0}}/><button type="submit" className="btnP wlBt" disabled={submitting||!agreed}>{submitting?"Submitting...":"Join waitlist"}</button></form><label className="pvL"><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)} required className="pvC"/><span>I agree to the <Link href="/privacy" className="pvLk">Privacy Notice</Link> and <Link href="/terms" className="pvLk">Terms</Link>.</span></label><div className="wlBadges"><span className="wlBadge"><Shield size={11}/>Privacy-first by design</span><span className="wlBadge"><Shield size={11}/>Built with UK data protection in mind</span></div>{success&&<div className="fmOk">{success}</div>}{error&&<div className="fmEr">{error}</div>}</div></FI></div></section>

      <footer className="ft"><div className="container ftIn"><div className="ftTop"><div><Link href="/" className="ftBr"><div className="navLo ftLoW"><Image src="/omela-logo-mark.png" alt="Omela" width={26} height={26} style={{width:"100%",height:"100%",objectFit:"contain"}}/></div><div><div className="ftBrN">Omela</div><div className="ftBrS">POWERED BY LAURA</div></div></Link></div><div className="ftCols"><div className="ftCol"><div className="ftColT">Product</div><Link href="/demo" className="ftLk">Try Laura</Link><Link href="/how-laura-helps" className="ftLk">Use cases</Link><Link href="/quiz" className="ftLk">Health Quiz</Link><Link href="/status" className="ftLk">Status</Link></div><div className="ftCol"><div className="ftColT">Legal</div><Link href="/privacy" className="ftLk">Privacy</Link><Link href="/terms" className="ftLk">Terms</Link><a href="mailto:notice@omela.ai" className="ftLk">Contact</a></div></div></div><div className="ftDsc">Laura is a care navigation assistant, not a medical professional. She does not provide diagnosis or treatment. For emergencies, call 999 or 911.</div><div className="ftBtm"><p>&copy; 2026 Omela.</p></div></div></footer>
    </div>
  </>);
}

const CSS=`
*{box-sizing:border-box;margin:0;padding:0}html{scroll-behavior:smooth}html,body{max-width:100%;overflow-x:clip}
body{background:${c.bg};color:${c.text};font-family:'DM Sans',-apple-system,sans-serif;-webkit-font-smoothing:antialiased;font-size:16px}
a{color:inherit;text-decoration:none}button,input,select{font-family:inherit}::selection{background:${c.accent};color:#fff}
@keyframes blink{0%,50%{opacity:1}50.01%,100%{opacity:0}}@keyframes tDot{0%,80%{opacity:0.3;transform:scale(0.8)}40%{opacity:1;transform:scale(1)}}
.serif{font-family:'Instrument Serif',Georgia,serif}.wrap{width:100%;overflow-x:clip}.container{max-width:1100px;margin:0 auto;padding:0 20px}
.sec{padding:68px 0}.secDk{padding:68px 0;background:${c.dark};color:#fff}.secPr{padding:68px 0;background:linear-gradient(180deg,#FDFCFA,${c.bg})}
.soon{display:inline-flex;padding:3px 8px;border-radius:6px;background:rgba(37,99,235,0.06);color:${c.accent};font-size:10px;font-weight:700;border:1px solid rgba(37,99,235,0.1)}
.stBar{background:${c.greenSoft};border-bottom:1px solid rgba(34,197,94,0.12);padding:6px 0}.stIn{display:flex;align-items:center;gap:7px}.stDot{width:6px;height:6px;border-radius:999px;background:${c.green};display:inline-block;box-shadow:0 0 5px ${c.green}44}.stLbl{font-size:12px;font-weight:700;color:${c.greenDk}}.stLnk{font-size:11px;font-weight:700;color:${c.accent};text-decoration:underline;text-underline-offset:2px}
.chk{width:18px;height:18px;border-radius:999px;background:${c.greenSoft};color:${c.green};display:inline-flex;align-items:center;justify-content:center;font-size:9px;font-weight:800;flex-shrink:0;margin-top:2px}.chkD{background:rgba(34,197,94,0.12);color:#4ADE80}
.shW{text-align:center;max-width:700px;margin:0 auto}.shT{font-size:clamp(24px,5vw,46px);line-height:1.08;letter-spacing:-0.04em}.shB{font-size:clamp(14px,2.5vw,16px);line-height:1.78;margin-top:12px;max-width:500px;margin-left:auto;margin-right:auto;color:${c.sub}}
.btnP{display:inline-flex;align-items:center;justify-content:center;gap:7px;background:${c.dark};color:#fff;border:none;border-radius:999px;padding:14px 24px;font-size:14px;font-weight:700;cursor:pointer;transition:all 0.3s;white-space:nowrap;box-shadow:0 2px 8px rgba(0,0,0,0.08)}.btnP:hover:not(:disabled){transform:translateY(-1px);box-shadow:0 8px 28px rgba(0,0,0,0.14)}.btnP:disabled{opacity:0.5;cursor:not-allowed;transform:none}
.btnS{display:inline-flex;align-items:center;justify-content:center;gap:7px;background:rgba(255,255,255,0.9);color:${c.text};border:1px solid ${c.border};border-radius:999px;padding:14px 24px;font-size:14px;font-weight:700;cursor:pointer;transition:all 0.3s;white-space:nowrap}.btnS:hover{background:#fff;box-shadow:0 4px 16px rgba(0,0,0,0.06)}
.nav{position:sticky;top:0;z-index:100;background:rgba(248,246,241,0.88);backdrop-filter:blur(24px);-webkit-backdrop-filter:blur(24px);border-bottom:1px solid rgba(227,221,210,0.5)}.navR{display:flex;align-items:center;justify-content:space-between;gap:8px;height:56px}.navBr{display:flex;align-items:center;gap:7px;flex-shrink:0}.navLo{width:32px;height:32px;border-radius:9px;overflow:hidden;flex-shrink:0;box-shadow:0 2px 6px rgba(0,0,0,0.05)}.navNm{font-size:14px;font-weight:800;letter-spacing:-0.03em}.navSb{font-size:8px;font-weight:800;letter-spacing:0.1em;color:${c.accent};margin-top:1px}.navLks{display:none;align-items:center;gap:22px}.navLk{font-size:13px;font-weight:600;color:${c.sub};transition:color 0.2s}.navLk:hover{color:${c.text}}.navCt{padding:9px 16px!important;font-size:12px!important;flex-shrink:0}
.heroSec{padding:48px 0 20px}.heroTxt{max-width:540px}.heroTi{font-size:clamp(34px,8.5vw,76px);line-height:0.96;letter-spacing:-0.05em}.heroAc{color:${c.accent};font-style:italic}.tw{font-size:clamp(16px,2.8vw,20px);line-height:1.5;color:${c.text};font-weight:600;min-height:1.4em;display:block;margin-top:16px}.twC{color:${c.accent};animation:blink 1s step-end infinite;font-weight:300}.heroSub{font-size:clamp(14px,2.2vw,16px);line-height:1.78;color:${c.sub};max-width:460px;margin-top:10px}.heroBd{min-height:44px}.heroBt{display:flex;flex-direction:column;gap:10px;margin-top:24px}.heroBt .btnP,.heroBt .btnS{width:100%;text-align:center}
.heroPh{margin-top:32px;width:100%;display:flex;justify-content:center;position:relative}
.phW{width:100%;max-width:220px;position:relative}.phGlow{position:absolute;inset:-28px;border-radius:999px;background:radial-gradient(circle,rgba(37,99,235,0.06),transparent 70%);z-index:0}.phF{position:relative;z-index:1}.phB{background:#1A1A1E;border-radius:30px;padding:4px;box-shadow:0 16px 40px rgba(0,0,0,0.14),0 2px 8px rgba(0,0,0,0.06)}.phDI{width:60px;height:16px;border-radius:999px;background:#000;margin:0 auto 2px}.phS{background:#FAFAFA;border-radius:27px;overflow:hidden}
.phH{display:flex;align-items:center;gap:4px;padding:5px 7px;background:#fff;border-bottom:1px solid #f0f0f0}.phAv{position:relative;width:20px;height:20px;border-radius:999px;overflow:hidden;flex-shrink:0;border:1px solid #fff}.phN{display:flex;align-items:center;gap:2px;font-size:9px;font-weight:700}.phOn{display:flex;align-items:center;gap:2px;font-size:7px;color:${c.green};font-weight:600}.phOnD{width:3px;height:3px;border-radius:999px;background:${c.green};display:inline-block}
.phLang{display:flex;align-items:center;justify-content:center;gap:3px;padding:3px 0;background:#F7F7FB;font-size:8px;font-weight:700;color:${c.accent}}
.phBdy{display:flex;flex-direction:column;gap:2px;padding:5px 4px;height:310px;overflow:hidden;justify-content:flex-end;background:linear-gradient(180deg,#F5F5F0,#ECE5DA)}
.phR{display:flex}.phRR{justify-content:flex-end}.phRL{justify-content:flex-start}
.phBb{max-width:88%;padding:5px 7px;font-size:8px;line-height:1.38;word-break:break-word}.phBbU{background:#E7FFDB;color:#111;border-radius:8px 8px 2px 8px}.phBbL{background:#fff;color:#111;border-radius:8px 8px 8px 2px}.phMt{display:flex;justify-content:flex-end;margin-top:1px}
.phAct{width:90%;margin:2px auto;padding:5px 7px;background:${c.accentSoft};border:1px solid rgba(37,99,235,0.1);border-radius:7px;font-size:7.5px;font-weight:700;color:${c.accent};text-align:center}
.phTy{display:flex;gap:2px;padding:7px 10px}.phTy span{width:4px;height:4px;border-radius:999px;background:${c.muted};animation:tDot 1.2s infinite}.phTy span:nth-child(2){animation-delay:0.2s}.phTy span:nth-child(3){animation-delay:0.4s}
.phCo{padding:3px 4px 6px;display:flex;align-items:center;gap:3px;background:#F0EBE3}.phCoF{flex:1;height:18px;border-radius:999px;background:#fff;display:flex;align-items:center;padding:0 6px}.phCoT{color:${c.muted};font-size:7px}.phCoM{width:18px;height:18px;border-radius:999px;background:#25D366;display:flex;align-items:center;justify-content:center;flex-shrink:0}
.capGrid{display:grid;grid-template-columns:1fr;gap:14px;margin-top:32px}.capCard{padding:28px;border:1px solid ${c.border};border-radius:22px;background:rgba(255,255,255,0.95);transition:all 0.3s}.capCard:hover{box-shadow:0 12px 36px rgba(0,0,0,0.06);transform:translateY(-2px)}.capIc{width:50px;height:50px;border-radius:14px;display:flex;align-items:center;justify-content:center;background:${c.accentSoft};color:${c.accent};border:1px solid rgba(37,99,235,0.08);margin-bottom:14px}.capTi{font-size:17px;font-weight:800;letter-spacing:-0.03em}.capBd{font-size:13.5px;line-height:1.72;color:${c.sub};margin-top:6px}
.seeAll{display:inline-flex;align-items:center;gap:5px;font-size:14px;font-weight:700;color:${c.accent}}
.baGrid{display:grid;grid-template-columns:1fr;gap:14px;margin-top:32px}.baCard{border-radius:22px;padding:28px;border:1px solid ${c.border}}.baBf{background:rgba(254,242,242,0.3)}.baAf{background:rgba(236,253,243,0.3)}.baTi{font-size:17px;font-weight:800;margin-bottom:16px}.baIt{display:flex;align-items:flex-start;gap:8px;font-size:13.5px;line-height:1.65;color:${c.sub};margin-bottom:10px}.baX{color:#EF4444;font-weight:800;flex-shrink:0;margin-top:1px}
.globeSec{padding:72px 0;background:linear-gradient(180deg,${c.bg},#EDE8DD,${c.bg})}.globeW{display:flex;flex-direction:column;align-items:center;gap:24px;margin-top:32px}.globeV{width:100%;max-width:340px;aspect-ratio:1;margin:0 auto}.globeCanvas{width:100%;height:100%;display:block}.globeC{width:100%;max-width:480px;text-align:center}.globeStory{min-height:180px}.globeCtry{display:flex;align-items:center;justify-content:center;gap:6px;margin-bottom:10px}.globeCtryN{font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:0.12em;color:${c.muted};background:rgba(255,255,255,0.8);padding:3px 9px;border-radius:5px}.globeQ{font-size:clamp(15px,3.2vw,20px);line-height:1.35;letter-spacing:-0.02em;font-style:italic}.globeNm{font-size:11px;color:${c.muted};font-weight:600;margin-top:8px;font-style:italic}.globeL{display:flex;align-items:flex-start;gap:8px;margin-top:14px;background:rgba(255,255,255,0.85);border:1px solid ${c.border};border-radius:14px;padding:12px 14px;text-align:left}.globeLA{position:relative;width:22px;height:22px;border-radius:999px;overflow:hidden;flex-shrink:0;border:1px solid #fff}.globeLT{font-size:12.5px;line-height:1.65;color:${c.sub}}.globeNav{display:flex;align-items:center;justify-content:center;gap:14px;margin-top:18px}.globeDs{display:flex;gap:4px}.globeD{width:6px;height:6px;border-radius:999px;background:${c.border};border:none;cursor:pointer;transition:all 0.3s;padding:0}.globeDA{background:${c.warm};width:18px}.globeAs{display:flex;gap:4px}.globeA{width:30px;height:30px;border-radius:999px;background:rgba(255,255,255,0.9);border:1px solid ${c.border};display:flex;align-items:center;justify-content:center;cursor:pointer;color:${c.sub}}
.audGrid{display:grid;grid-template-columns:1fr;gap:14px;margin-top:32px}.audCard{padding:28px;border:1px solid ${c.border};border-radius:22px;background:rgba(255,255,255,0.95);transition:all 0.3s}.audCard:hover{box-shadow:0 8px 28px rgba(0,0,0,0.05)}.audIc{width:50px;height:50px;border-radius:14px;display:flex;align-items:center;justify-content:center;margin-bottom:14px;border:1px solid rgba(0,0,0,0.04)}.audTi{font-size:18px;font-weight:800;letter-spacing:-0.03em}.audBd{font-size:13.5px;line-height:1.78;color:${c.sub};margin-top:8px}
.g2{display:grid;grid-template-columns:1fr;gap:16px}
.dkC{background:linear-gradient(180deg,rgba(16,19,24,0.98),rgba(13,15,20,0.98));border:1px solid ${c.borderDk};border-radius:22px;padding:28px}.dkCT{font-size:clamp(17px,3vw,22px);font-weight:800;color:#fff}.dkCB{margin-top:8px;color:rgba(255,255,255,0.5);font-size:13.5px;line-height:1.8}
.ftL{display:flex;flex-direction:column;gap:6px;margin-top:10px}.ftR{display:flex;align-items:flex-start;gap:6px;font-size:13px;line-height:1.55;color:${c.sub}}
.glC{border:1px solid ${c.border};background:rgba(255,255,255,0.92);border-radius:22px;padding:28px;text-align:center}.glT{font-size:clamp(22px,4.5vw,38px);letter-spacing:-0.04em;display:inline}.glB{margin-top:8px;color:${c.sub};font-size:14px;line-height:1.75;max-width:440px;margin-left:auto;margin-right:auto}.glF{display:flex;flex-wrap:wrap;justify-content:center;gap:6px;margin-top:16px}.glFi{padding:6px 12px;border-radius:999px;border:1px solid ${c.border};background:rgba(255,255,255,0.8);font-size:11px;font-weight:600;color:${c.sub}}
/* Terminal FIXED */
.trm{background:#07080B;border:1px solid #1F2330;border-radius:16px;overflow:hidden;height:340px;display:flex;flex-direction:column}.trmT{display:flex;align-items:center;gap:6px;padding:10px 13px;border-bottom:1px solid #1B1F2B;background:#0E1118;flex-shrink:0}.trmD{display:flex;gap:4px}.trmD span{width:7px;height:7px;border-radius:999px;display:inline-block}.trmD span:nth-child(1){background:#FF5F57}.trmD span:nth-child(2){background:#FEBC2E}.trmD span:nth-child(3){background:#28C840}.trmTi{font-size:9px;color:#6B7280;font-weight:700;flex:1}.trmB{padding:12px;flex:1;overflow:hidden}.trmL{white-space:pre-wrap;word-break:break-all;font-size:10px;line-height:1.7;font-family:'SF Mono',ui-monospace,Menlo,Consolas,monospace}.trmC{color:#60A5FA;animation:blink 0.8s step-end infinite}
/* Roadmap dark cards */
.roadScroll{display:flex;gap:14px;margin-top:32px;overflow-x:auto;scroll-snap-type:x mandatory;-webkit-overflow-scrolling:touch;padding-bottom:8px;scrollbar-width:none;-ms-overflow-style:none}.roadScroll::-webkit-scrollbar{display:none}
.roadCard{min-width:260px;max-width:300px;flex-shrink:0;scroll-snap-align:start;background:linear-gradient(160deg,#111318,#0A0C10);border:1px solid rgba(255,255,255,0.06);border-radius:18px;padding:24px;position:relative;overflow:hidden;transition:all 0.3s}.roadCard:hover{border-color:rgba(201,149,107,0.2);box-shadow:0 8px 32px rgba(0,0,0,0.3)}
.roadTop{display:flex;align-items:center;justify-content:space-between;margin-bottom:14px}
.roadEmoji{font-size:28px;display:block}
.roadSt{padding:4px 10px;border-radius:999px;background:rgba(201,149,107,0.12);color:${c.warm};font-size:10px;font-weight:700;border:1px solid rgba(201,149,107,0.15)}
.roadTi{font-size:15px;font-weight:800;color:#fff;letter-spacing:-0.02em}.roadDs{font-size:12px;line-height:1.65;color:rgba(255,255,255,0.45);margin-top:6px}
.roadLine{position:absolute;bottom:0;left:24px;right:24px;height:2px;background:linear-gradient(90deg,transparent,rgba(201,149,107,0.2),transparent);border-radius:1px}
.roadNote{text-align:center;font-size:12px;color:${c.muted};margin-top:20px;font-style:italic}
/* Infra */
.infraSec{padding:40px 0;border-top:1px solid ${c.border};border-bottom:1px solid ${c.border}}
.infraIn{text-align:center}.infraLbl{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.12em;color:${c.muted};margin-bottom:20px}
.infraGrid{display:flex;align-items:center;justify-content:center;gap:24px;flex-wrap:wrap}
.infraItem{display:flex;align-items:center;justify-content:center}
.infraLogo{width:80px;height:28px;position:relative;display:flex;align-items:center;justify-content:center;opacity:0.5;transition:opacity 0.3s}.infraLogo:hover{opacity:0.8}
/* Pricing */
.prGrid{display:grid;grid-template-columns:1fr;gap:14px;margin-top:36px}.prCard{background:rgba(255,255,255,0.96);border:1px solid ${c.border};border-radius:22px;padding:32px;position:relative;transition:all 0.3s;display:flex;flex-direction:column}.prCard:hover{box-shadow:0 12px 36px rgba(0,0,0,0.06)}.prCardDk{background:linear-gradient(180deg,#111318,#0D0F14)!important;border:1px solid ${c.borderDk}!important;color:#fff!important}.prBg{position:absolute;top:14px;right:14px;border-radius:6px;padding:4px 10px;background:rgba(255,255,255,0.1);color:rgba(255,255,255,0.6);font-size:9px;font-weight:700}.prNm{font-size:16px;font-weight:800}.prPr{margin-top:10px}.prAmt{font-size:clamp(24px,5vw,36px);letter-spacing:-0.04em}.prPd2{font-size:12px;color:${c.muted};margin-top:3px}.prCardDk .prPd2{color:rgba(255,255,255,0.35)}.prDs{margin-top:10px;font-size:13.5px;line-height:1.72;color:${c.sub}}.prCardDk .prDs{color:rgba(255,255,255,0.5)}
.prFts{display:flex;flex-direction:column;gap:7px;margin-top:18px;padding-top:18px;border-top:1px solid ${c.border};flex:1}.prCardDk .prFts{border-top-color:rgba(255,255,255,0.08)}
.prFt{display:flex;align-items:flex-start;gap:6px;font-size:12.5px;line-height:1.5;color:${c.sub}}.prCardDk .prFt{color:rgba(255,255,255,0.6)}
.prBt{margin-top:20px;width:100%}.prBtW{background:#fff!important;color:${c.dark}!important}
/* Waitlist */
.wlC{background:rgba(255,255,255,0.95);border:1px solid ${c.border};border-radius:22px;padding:28px;max-width:720px;margin:0 auto;box-shadow:0 4px 20px rgba(0,0,0,0.03)}.wlF{display:grid;grid-template-columns:1fr;gap:10px;margin-top:16px}.wlBt{height:48px;width:100%}.inp{width:100%;height:48px;border-radius:12px;border:1px solid ${c.border};background:#fff;padding:0 14px;font-size:14px;color:${c.text};outline:none;transition:all 0.2s}.inp:focus{border-color:${c.accent};box-shadow:0 0 0 3px rgba(37,99,235,0.06)}
.pvL{display:flex;align-items:flex-start;gap:6px;margin-top:10px;color:${c.sub};font-size:11px;line-height:1.6;cursor:pointer;max-width:480px;margin-left:auto;margin-right:auto}.pvC{margin-top:1px;width:14px;height:14px;accent-color:${c.accent};flex-shrink:0}.pvLk{color:${c.text};font-weight:700;text-decoration:underline;text-underline-offset:2px}
.wlBadges{display:flex;gap:6px;justify-content:center;margin-top:14px;flex-wrap:wrap}.wlBadge{display:inline-flex;align-items:center;gap:4px;padding:4px 10px;border-radius:8px;background:rgba(37,99,235,0.04);border:1px solid rgba(37,99,235,0.08);color:${c.accent};font-size:10px;font-weight:700}
.fmOk{margin-top:10px;background:${c.greenSoft};color:${c.greenDk};border-radius:12px;padding:12px;text-align:center;font-size:13px;font-weight:600}.fmEr{margin-top:10px;background:#FFF7F7;color:#B91C1C;border-radius:12px;padding:12px;text-align:center;font-size:13px;font-weight:600}
/* Modal */
.modO{position:fixed;inset:0;z-index:220;background:rgba(9,10,13,0.5);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);display:flex;align-items:center;justify-content:center;padding:14px}
.modB{width:100%;max-width:420px;background:rgba(255,255,255,0.98);border:1px solid ${c.border};border-radius:24px;padding:32px;box-shadow:0 24px 60px rgba(0,0,0,0.18);position:relative;overflow:hidden;text-align:center}
.modCel{width:56px;height:56px;border-radius:999px;background:linear-gradient(135deg,#FFF8F0,#ECFDF3);border:1px solid rgba(34,197,94,0.15);display:flex;align-items:center;justify-content:center;margin:0 auto 16px}.modCelE{font-size:28px}
.modTi{font-size:clamp(22px,4.5vw,30px);letter-spacing:-0.04em}.modBd{margin-top:8px;color:${c.sub};font-size:13.5px;line-height:1.72}
.modRef{margin-top:20px;padding:16px;border-radius:14px;background:rgba(37,99,235,0.03);border:1px solid rgba(37,99,235,0.08)}
.modRefLbl{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:0.1em;color:${c.muted};margin-bottom:8px}
.modRefBox{display:flex;align-items:center;gap:8px;background:#fff;border:1px solid ${c.border};border-radius:10px;padding:8px 10px}
.modRefUrl{flex:1;font-size:11px;color:${c.sub};font-weight:500;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-align:left}
.modRefCp{width:32px;height:32px;border-radius:8px;background:${c.accentSoft};border:1px solid rgba(37,99,235,0.1);color:${c.accent};display:flex;align-items:center;justify-content:center;cursor:pointer;flex-shrink:0;transition:all 0.2s}.modRefCp:hover{background:rgba(37,99,235,0.12)}
.modRefBts{display:flex;gap:8px;margin-top:12px}.modShareBtn{flex:1;padding:10px 14px!important;font-size:12px!important}.modXBtn{flex:1;padding:10px 14px!important;font-size:12px!important}
.modClose{margin-top:14px;background:none;border:none;color:${c.muted};font-size:12px;font-weight:600;cursor:pointer;padding:4px 8px}
.confW{position:absolute;inset:0;pointer-events:none;overflow:hidden}.confP{position:absolute;bottom:40%;font-size:16px;pointer-events:none}
/* Footer */
.ft{background:${c.dark};padding:36px 0 20px;color:#fff}.ftTop{display:flex;flex-direction:column;gap:24px}.ftBr{display:flex;align-items:center;gap:7px;text-decoration:none;color:#fff}.ftLoW{background:rgba(255,255,255,0.12);border-radius:9px;padding:2px}.ftBrN{font-size:13px;font-weight:800}.ftBrS{font-size:8px;font-weight:800;letter-spacing:0.1em;color:${c.accent};margin-top:1px}.ftCols{display:flex;gap:36px}.ftCol{display:flex;flex-direction:column;gap:7px}.ftColT{font-size:10px;font-weight:800;color:rgba(255,255,255,0.3);text-transform:uppercase;letter-spacing:0.1em;margin-bottom:3px}.ftLk{font-size:12px;color:rgba(255,255,255,0.5);font-weight:500;transition:color 0.2s}.ftLk:hover{color:#fff}
.ftDsc{margin-top:24px;padding:14px 0;border-top:1px solid rgba(255,255,255,0.06);font-size:11px;color:rgba(255,255,255,0.3);line-height:1.7;text-align:center}
.ftBtm{border-top:1px solid rgba(255,255,255,0.06);padding-top:14px;font-size:10px;color:rgba(255,255,255,0.2);text-align:center}
@media(min-width:640px){.container{padding:0 24px}.sec{padding:80px 0}.secDk{padding:80px 0}.secPr{padding:80px 0}.navR{height:64px}.navLks{display:flex}.heroBt{flex-direction:row}.heroBt .btnP,.heroBt .btnS{width:auto}.capGrid{grid-template-columns:repeat(3,1fr)}.baGrid{grid-template-columns:repeat(2,1fr)}.audGrid{grid-template-columns:repeat(3,1fr)}.prGrid{grid-template-columns:repeat(3,1fr)}.g2{grid-template-columns:repeat(2,1fr);gap:20px}.wlF{grid-template-columns:1.2fr 0.8fr auto}.wlBt{width:auto}.wlC{padding:32px}.phW{max-width:240px}.ftTop{flex-direction:row;justify-content:space-between}.globeW{flex-direction:row;align-items:center;gap:36px}.globeV{max-width:340px;flex-shrink:0}.globeC{text-align:left}.globeCtry{justify-content:flex-start}.globeQ{text-align:left}.globeNm{text-align:left}.infraLogo{width:100px;height:32px}.roadCard{min-width:280px}.infraGrid{gap:32px}}
@media(min-width:960px){.container{padding:0 36px}.sec{padding:92px 0}.secDk{padding:92px 0}.secPr{padding:92px 0}.navR{height:72px}.heroSec{padding:60px 0 32px}.heroSec .container{display:grid;grid-template-columns:1.1fr 0.9fr;gap:0 40px;align-items:start}.heroTxt{grid-column:1}.heroPh{grid-column:2;margin-top:0;align-self:start}.phW{max-width:260px}.phB{border-radius:36px;padding:5px}.phS{border-radius:32px}.phBdy{height:340px}.globeV{max-width:380px}.infraGrid{gap:40px}.infraLogo{width:110px;height:36px}}
@media(min-width:1100px){.heroTi{font-size:clamp(56px,7vw,76px)}}
`;
